@extends('development.layout',['wizard'=>$step===5?4:($step===4?3:2)])
@section('title',$step===5?'Review & Consent':'Take a Brief Assessment')
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ $step===5?'REVIEW & CONSENT':'ASSESSMENT · PART '.$step.' OF 4' }}</p><h1>{{ $step===5?'Review, Consent and Continue':($step===4?'Tell Us More About Your Child':'Take a Brief Assessment') }}</h1><p>{{ $child->name }} · Age {{ $child->age }} · {{ $child->grade }}</p></div>@include('development.stepper',['wizard'=>$step===5?4:($step===4?3:2)])</div>
<form method="post" action="{{ route('development.assessment.save',[$child,$step]) }}">@csrf
@if($step<5)
<div class="notice lavender"><strong>Every child is unique.</strong> Your responses help us understand their learning, emotional and social needs. Progress is saved when you select Next.</div>
<div class="grid two questions">@foreach(config('development.questions.'.$step) as $key=>[$label,$type,$options])<fieldset class="card {{ in_array($key,['reasons','goals','support'])?'span-two':'' }}"><legend>{{ $label }}</legend>
@if($type==='text')<textarea name="{{ $key }}" maxlength="500" rows="3" data-counter>{{ old($key,data_get($assessment?->answers,$key)) }}</textarea><small class="counter">0/500</small>
@else<p class="muted">{{ $type==='goals'?'Select up to 3.':($type==='multi'?'Select all that apply.':'Select one.') }}</p><div class="choices" @if($type==='goals') data-max="3" @endif>@foreach($options as $option)<label class="choice"><input type="{{ in_array($type,['multi','goals'])?'checkbox':'radio' }}" name="{{ $key }}{{ in_array($type,['multi','goals'])?'[]':'' }}" value="{{ $option }}" @checked(in_array($option,(array)old($key,data_get($assessment?->answers,$key,[]))))><span>{{ $option }}</span></label>@endforeach</div>@endif</fieldset>@endforeach</div>
@else
<div class="grid two"><section class="card"><div class="section-heading"><h2>Summary of Your Child’s Information</h2><a href="{{ route('development.assessment',[$child,1]) }}">Edit answers</a></div><dl class="summary"><div><dt>Child’s name</dt><dd>{{ $child->name }}</dd></div><div><dt>Age / Grade</dt><dd>{{ $child->age }} / {{ $child->grade }}</dd></div>@foreach(['education'=>'Education Level','environment'=>'Learning Environment','support'=>'Support Areas','health'=>'Additional Needs','heard'=>'How You Heard About VALYNK'] as $key=>$label)<div><dt>{{ $label }}</dt><dd>{{ implode(', ',(array)data_get($assessment->answers,$key,[])) }}</dd></div>@endforeach</dl></section><section class="card"><h2>Parental Consent</h2>@foreach(['guardian'=>'I am the parent or legal guardian, or an adult completing my own profile.','consent'=>'I consent to VALYNK storing these answers and generating a summary of the support needs I have described.','sharing'=>'I understand that sharing with a provider requires a separate connection request.'] as $key=>$label)<label class="check-row"><input type="checkbox" name="{{ $key }}" value="1" required @checked(old($key))>{{ $label }}</label>@endforeach<div class="notice lavender"><h3>Your information is safe</h3><p>Assessment answers are private to your account. The report summarises your observations; it is not a clinical assessment.</p></div></section></div>
@endif
<div class="form-actions"><a class="button secondary" href="{{ $step>1?route('development.assessment',[$child,$step-1]):route('development.home') }}">← Back</a><button class="button">{{ $step===5?'Generate My Summary & Find Providers':'Next' }} →</button><a href="{{ route('contact') }}">Need help?</a></div></form>
@endsection
