@extends('development.layout',['wizard'=>1])
@section('title',$register?'Create Your Account':'Add a Child')
@section('content')
<div class="page-heading"><div><p class="eyebrow">STEP 1 OF 4</p><h1>{{ $register?'Create Your Account':'Tell Us About Your Child' }}</h1><p>Let’s get to know you and your child.</p></div>@include('development.stepper',['wizard'=>1])</div>
<div class="grid main-aside"><form class="card" method="post" action="{{ route($register?'development.register.store':'development.child.store') }}">@csrf
@if($register)<h2>Parent / Guardian Details</h2><div class="grid two fields">@foreach(['name'=>'Full Name','phone'=>'Phone Number','email'=>'Email Address','password'=>'Create Password','password_confirmation'=>'Confirm Password'] as $key=>$label)<label>{{ $label }} <span class="required">*</span><input name="{{ $key }}" type="{{ str_contains($key,'password')?'password':($key==='email'?'email':($key==='phone'?'tel':'text')) }}" value="{{ str_contains($key,'password')?'':old($key) }}" required @if(str_contains($key,'password')) minlength="12" autocomplete="new-password" @endif></label>@endforeach</div><p class="muted">Use at least 12 characters for your password.</p><hr>@endif
<h2>Child’s Details</h2><div class="grid two fields"><label>Child’s Full Name *<input name="child_name" value="{{ old('child_name') }}" required maxlength="120"></label><label>Child’s Age *<select name="age" required><option value="">Select age</option>@foreach(range(5,25) as $age)<option value="{{ $age }}" @selected(old('age')==$age)>{{ $age }} years</option>@endforeach</select></label><label>Grade / Level *<input name="grade" value="{{ old('grade') }}" placeholder="e.g. Grade 5" maxlength="60" required></label><label>School (optional)<input name="school" value="{{ old('school') }}" maxlength="150"></label></div>
@if($register)<label class="check-row"><input type="checkbox" name="terms" value="1" required @checked(old('terms'))> I agree to the account terms and consent to storing these family details for support and assessment.</label><details><summary>How we use this information</summary><p>Your account stores your child’s profile and your assessment answers. Provider sharing requires a separate confirmation. Contact support to request changes or deletion.</p></details>@endif
<button class="button wide">{{ $register?'Create Account & Continue':'Save Child & Begin Assessment' }} →</button>@if($register)<p class="center">Already have an account? <a href="{{ route('login') }}">Log in</a></p>@endif</form>
<aside class="card warm"><h2>What Happens Next?</h2><ol class="next-steps">@foreach(['Create your family profile','Take a brief assessment','Review your child’s needs','Explore relevant providers'] as $text)<li><span>{{ $loop->iteration }}</span><div><h3>{{ $text }}</h3><p>{{ ['Start with your child’s details.','Share their interests, needs and goals.','Get a clear summary of your observations.','Choose who you want to connect with.'][$loop->index] }}</p></div></li>@endforeach</ol></aside></div>
@endsection
