@extends('development.layout')
@section('title',$sample?'Sample Full Report':'Child Support Report')
@section('content')
@php($childName=$sample?'Amina Wanjiku':$assessment->child->name)
<div class="page-heading"><div><p class="eyebrow">{{ $sample?'SAMPLE REPORT · DEMONSTRATION ONLY':'YOUR CHILD’S SUPPORT SUMMARY' }}</p><h1>Full Report</h1><p>{{ $childName }} · Age {{ $sample?10:$assessment->child->age }} · {{ $sample?'Grade 5':$assessment->child->grade }}</p></div><div class="actions">@if($sample)<a class="button secondary" href="{{ route('development.sample.pdf') }}">↓ Download Sample PDF</a>@endif<button class="button secondary" data-print>Print / Save PDF</button></div></div>
<div class="tabs" data-tabs><button aria-selected="true" data-tab="summary">Summary</button><button aria-selected="false" data-tab="strengths">Strengths & Goals</button><button aria-selected="false" data-tab="growth">Growth Areas</button><button aria-selected="false" data-tab="details">Detailed Results</button><button aria-selected="false" data-tab="recommendations">Recommendations</button></div>
@if($sample)
<div class="notice">Illustrative scores from the supplied sample report. These are not clinical, psychological or educational diagnoses.</div>
<section data-panel="summary"><div class="grid main-aside"><div class="card"><h2>Overall Development Profile</h2><div class="profile-score"><div class="ring" style="--score:78"><strong>78%<small>Overall Development<br>Score</small></strong></div><div><p>Amina shows strong curiosity, learning attitude and positive social skills. Focused support in time management and emotional regulation can help her thrive.</p><ul class="checks"><li>4 strength areas</li><li>3 developing areas</li><li>1 priority support area</li></ul></div></div></div><div class="card warm"><h2>Amina’s Potential</h2><p>With the right guidance and support, Amina can build confidence, develop key skills and achieve her goals.</p><p class="tagline">More Possibilities.<br>Brighter Futures.</p></div></div><div class="grid three"><section class="card"><h2>Development Area Scores</h2>@foreach(['Cognitive Skills'=>85,'Emotional Regulation'=>70,'Social Skills'=>80,'Focus & Concentration'=>75,'Time Management'=>65,'Self-Confidence'=>78,'Learning Attitude'=>82] as $label=>$score)<div class="bar-row"><span>{{ $label }}</span><progress value="{{ $score }}" max="100">{{ $score }}%</progress><b>{{ $score }}%</b></div>@endforeach</section><section class="card"><h2>Key Strengths</h2><ul class="feature-list">@foreach(['Curiosity & Learning Potential','Creativity','Positive Social Skills','Learning Attitude'] as $s)<li><span class="icon">✦</span>{{ $s }}</li>@endforeach</ul></section><section class="card"><h2>Growth Areas</h2><ul class="feature-list">@foreach(['Time Management','Emotional Regulation','Study Skills'] as $s)<li><span class="icon">↗</span>{{ $s }}</li>@endforeach</ul></section></div></section>
<section class="card" data-panel="strengths" hidden><h2>Build on What Is Working</h2><p>Curiosity, creativity, positive social skills and a strong learning attitude provide a foundation for growth. Continue collaborative projects, creative exploration and learning opportunities.</p></section><section class="card" data-panel="growth" hidden><h2>Prioritise Practical Growth</h2><ul class="checks"><li>Time management: practise planning and prioritising tasks.</li><li>Emotional regulation: build strategies for frustration and setbacks.</li><li>Study routines: create a consistent, distraction-aware routine.</li></ul></section><section class="card" data-panel="details" hidden><h2>Detailed Development Profile</h2><p>The complete six-page sample explains the development profile, recommendations, provider-match evidence and reassessment plan.</p><a class="button" href="{{ route('development.sample.pdf') }}">Download Full Sample Report →</a></section><section class="card" data-panel="recommendations" hidden><h2>Suggested 90-Day Sequence</h2><div class="grid three">@foreach(['Days 1–30'=>'Baseline routines, confidence and goal clarity.','Days 31–60'=>'Focus, discipline and emotional regulation.','Days 61–90'=>'Application and independent execution.'] as $label=>$text)<article class="tint"><h3>{{ $label }}</h3><p>{{ $text }}</p></article>@endforeach</div></section>
@else
<section data-panel="summary"><div class="grid two"><div class="card"><h2>Support Priorities</h2><p>Based on your assessment completed {{ $assessment->consented_at->format('d M Y') }}.</p><ul class="checks">@foreach(data_get($assessment->answers,'support',[]) as $s)<li>{{ $s }}</li>@endforeach</ul></div><div class="card lavender"><h2>Your Goals for {{ $childName }}</h2><ul class="checks">@foreach(data_get($assessment->answers,'goals',[]) as $s)<li>{{ $s }}</li>@endforeach</ul></div></div><div class="notice">This summary reflects your answers. No development or match percentage has been assigned.</div></section>
<section class="card" data-panel="strengths" hidden><h2>Learning Preferences & Goals</h2><p>{{ implode(', ',data_get($assessment->answers,'learning',[])) }}</p><ul class="checks">@foreach(data_get($assessment->answers,'goals',[]) as $s)<li>{{ $s }}</li>@endforeach</ul></section><section class="card" data-panel="growth" hidden><h2>Areas You Would Like Support With</h2><ul class="checks">@foreach(data_get($assessment->answers,'challenges',[]) as $s)<li>{{ $s }}</li>@endforeach</ul></section><section class="card" data-panel="details" hidden><h2>Your Assessment Responses</h2><dl class="summary">@foreach(config('development.questions') as $questions)@foreach($questions as $key=>[$label,$type,$options])<div><dt>{{ $label }}</dt><dd>{{ implode(', ',(array)data_get($assessment->answers,$key,[])) ?: 'Not provided' }}</dd></div>@endforeach @endforeach</dl></section><section class="card" data-panel="recommendations" hidden><h2>Your Next Steps</h2><ol class="checks"><li>Discuss your priorities and goals with your child.</li><li>Compare provider services with the support areas you selected.</li><li>Confirm availability, fees and suitability before making a booking.</li><li>Review progress together after support begins.</li></ol></section>
@endif
<section class="callout"><div><h2>Ready to Take the Next Step?</h2><p>Explore providers and choose relevant support for your child.</p></div><a class="button" href="{{ $sample?route('development.preview','providers'):route('development.providers') }}">View Providers →</a></section>
@endsection
