<?php

return [
    'performance-confidence' => [
        'title' => 'Performance, Confidence & Personal Development',
        'description' => 'Build the mindset, habits and personal capabilities for consistent high performance and a fulfilling life.',
        'tone' => 'pink',
        'icon' => 'chart-line',
        'photo' => 0,
        'image_url' => null,
        'tagline' => 'Confident. Capable. Prepared for what’s next.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Stronger Mindset',
            'Better Habits',
            'Greater Confidence',
            'Real Life Readiness',
        ],
        'benefits' => [
            'Greater self-confidence and resilience',
            'Improved focus and discipline',
            'Clearer sense of purpose and direction',
            'Stronger relationships and communication',
            'Higher performance in school, life and future opportunities',
        ],
        'support_intro' => 'Four core areas that build a stronger, more resilient and high-performing future.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'development.landing',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Positive Mindset & Self-Belief',
                'points' => [
                    'Growth mindset and resilience',
                    'Healthy self-talk and identity',
                    'Overcoming limiting beliefs',
                    'Confidence in new situations',
                ],
                'image_url' => null,
                'photo' => 0,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Focus, Discipline & Performance Habits',
                'points' => [
                    'Improved concentration',
                    'Time management skills',
                    'Consistent study and work habits',
                    'Reduced distractions',
                ],
                'image_url' => null,
                'photo' => 1,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Motivation, Purpose & Goal Achievement',
                'points' => [
                    'Clarity of purpose and direction',
                    'Setting and achieving meaningful goals',
                    'Persistence and grit',
                    'Turning potential into action',
                ],
                'image_url' => null,
                'photo' => 2,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Relationships, Communication & Social Confidence',
                'points' => [
                    'Effective communication skills',
                    'Positive peer and family relationships',
                    'Leadership and teamwork',
                    'Confidence in social and public settings',
                ],
                'image_url' => null,
                'photo' => 3,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'academic-learning' => [
        'title' => 'Academic, Learning & Excellence',
        'description' => 'Strengthen subject mastery, learning skills and exam performance for long-term academic success.',
        'tone' => 'blue',
        'icon' => 'book-open',
        'photo' => 1,
        'image_url' => null,
        'tagline' => 'Exam Readiness. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Subject Mastery',
            'Study Skills',
            'Learning Confidence',
            'Exam Readiness',
        ],
        'benefits' => [
            'Stronger understanding of core subjects',
            'More effective study habits',
            'Greater confidence in learning',
            'Better preparation for assessments',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Subject Mastery',
                'points' => [
                    'Targeted subject support',
                    'Build strong foundations',
                    'Close learning gaps',
                    'Practise with feedback',
                ],
                'image_url' => null,
                'photo' => 1,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Study Skills',
                'points' => [
                    'Plan effective study sessions',
                    'Improve organisation',
                    'Build independent learning habits',
                    'Use active recall',
                ],
                'image_url' => null,
                'photo' => 1,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Exam Preparation',
                'points' => [
                    'Revision planning',
                    'Exam technique',
                    'Timed practice',
                    'Manage exam pressure',
                ],
                'image_url' => null,
                'photo' => 1,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Learning Confidence',
                'points' => [
                    'Understand learning preferences',
                    'Ask questions confidently',
                    'Celebrate progress',
                    'Set realistic learning goals',
                ],
                'image_url' => null,
                'photo' => 1,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'career-discovery' => [
        'title' => 'Career Discovery, Education & Future Direction',
        'description' => 'Explore interests, discover opportunities and make informed education and career choices.',
        'tone' => 'green',
        'icon' => 'compass',
        'photo' => 2,
        'image_url' => null,
        'tagline' => 'Future Readiness. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Discover Strengths',
            'Explore Pathways',
            'Clearer Direction',
            'Future Readiness',
        ],
        'benefits' => [
            'A clearer understanding of interests and strengths',
            'Informed education choices',
            'Confidence exploring career options',
            'A practical plan for the next stage',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Interests & Strengths',
                'points' => [
                    'Explore personal interests',
                    'Identify strengths',
                    'Reflect on values',
                    'Discover new possibilities',
                ],
                'image_url' => null,
                'photo' => 2,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Education Pathways',
                'points' => [
                    'Compare subject choices',
                    'Understand qualifications',
                    'Explore further education',
                    'Plan the next stage',
                ],
                'image_url' => null,
                'photo' => 2,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Career Exploration',
                'points' => [
                    'Discover career areas',
                    'Understand work environments',
                    'Meet role models',
                    'Explore future opportunities',
                ],
                'image_url' => null,
                'photo' => 2,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Future Planning',
                'points' => [
                    'Set achievable goals',
                    'Build a personal action plan',
                    'Develop decision-making skills',
                    'Review progress',
                ],
                'image_url' => null,
                'photo' => 2,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'talent-ability' => [
        'title' => 'Talent & Ability Development',
        'description' => 'Nurture natural ability, develop specialist skills and unlock exceptional potential.',
        'tone' => 'gold',
        'icon' => 'star',
        'photo' => 3,
        'image_url' => null,
        'tagline' => 'Personal Growth. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Discover Talent',
            'Develop Skills',
            'Creative Confidence',
            'Personal Growth',
        ],
        'benefits' => [
            'Greater confidence in natural abilities',
            'Specialist skills developed through practice',
            'More opportunities for creative expression',
            'A clear path for continued growth',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Discover Your Talent',
                'points' => [
                    'Explore creative interests',
                    'Recognise natural strengths',
                    'Try new activities',
                    'Find the right mentor',
                ],
                'image_url' => null,
                'photo' => 3,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Creative Expression',
                'points' => [
                    'Music and performing arts',
                    'Visual arts and design',
                    'Creative practice',
                    'Build a portfolio',
                ],
                'image_url' => null,
                'photo' => 3,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Sport & Specialist Skills',
                'points' => [
                    'Develop technique',
                    'Build consistent practice',
                    'Team participation',
                    'Personal performance goals',
                ],
                'image_url' => null,
                'photo' => 3,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Showcase & Progress',
                'points' => [
                    'Prepare for performances',
                    'Receive constructive feedback',
                    'Celebrate achievements',
                    'Plan continued development',
                ],
                'image_url' => null,
                'photo' => 3,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'leadership-life' => [
        'title' => 'Leadership & Life Capabilities',
        'description' => 'Build essential life skills, leadership qualities and independence for greater impact.',
        'tone' => 'purple',
        'icon' => 'people-group',
        'photo' => 4,
        'image_url' => null,
        'tagline' => 'Work Together. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Lead Confidently',
            'Communicate Clearly',
            'Build Independence',
            'Work Together',
        ],
        'benefits' => [
            'Greater independence and responsibility',
            'Stronger communication skills',
            'Confidence working with others',
            'Practical preparation for everyday life',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Personal Leadership',
                'points' => [
                    'Take responsibility',
                    'Make thoughtful decisions',
                    'Set personal goals',
                    'Lead by example',
                ],
                'image_url' => null,
                'photo' => 4,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Communication',
                'points' => [
                    'Express ideas clearly',
                    'Listen actively',
                    'Speak with confidence',
                    'Give helpful feedback',
                ],
                'image_url' => null,
                'photo' => 4,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Everyday Independence',
                'points' => [
                    'Plan and organise tasks',
                    'Manage time',
                    'Solve everyday problems',
                    'Build practical life skills',
                ],
                'image_url' => null,
                'photo' => 4,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Teamwork & Community',
                'points' => [
                    'Collaborate with others',
                    'Respect different perspectives',
                    'Resolve disagreements',
                    'Contribute to the community',
                ],
                'image_url' => null,
                'photo' => 4,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'wellbeing' => [
        'title' => 'Emotional, Mental & Physical Wellbeing',
        'description' => 'Support a healthy mind, body and emotional balance for a positive and successful life.',
        'tone' => 'teal',
        'icon' => 'heart',
        'photo' => 5,
        'image_url' => null,
        'tagline' => 'Positive Connections. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Healthy Mind',
            'Healthy Body',
            'Emotional Balance',
            'Positive Connections',
        ],
        'benefits' => [
            'Better awareness of emotional needs',
            'Positive daily routines',
            'Stronger coping and resilience skills',
            'More supportive relationships',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Emotional Awareness',
                'points' => [
                    'Recognise emotions',
                    'Express feelings safely',
                    'Build coping strategies',
                    'Ask for support',
                ],
                'image_url' => null,
                'photo' => 5,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Mental Wellbeing',
                'points' => [
                    'Manage everyday stress',
                    'Build resilience',
                    'Develop healthy routines',
                    'Strengthen self-esteem',
                ],
                'image_url' => null,
                'photo' => 5,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Physical Wellbeing',
                'points' => [
                    'Enjoy regular movement',
                    'Build healthy daily habits',
                    'Balance activity and rest',
                    'Set wellbeing goals',
                ],
                'image_url' => null,
                'photo' => 5,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Social Connection',
                'points' => [
                    'Build supportive relationships',
                    'Develop empathy',
                    'Communicate personal needs',
                    'Create a sense of belonging',
                ],
                'image_url' => null,
                'photo' => 5,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'digital-skills' => [
        'title' => 'Digital & Future Skills',
        'description' => 'Develop the digital, technological and entrepreneurial skills needed for tomorrow’s opportunities.',
        'tone' => 'pink',
        'icon' => 'laptop',
        'photo' => 6,
        'image_url' => null,
        'tagline' => 'Future Readiness. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Digital Confidence',
            'Creative Thinking',
            'Online Safety',
            'Future Readiness',
        ],
        'benefits' => [
            'Confidence using digital tools',
            'Stronger creative problem-solving skills',
            'Safer online habits',
            'Preparation for a changing world',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Digital Confidence',
                'points' => [
                    'Use everyday digital tools',
                    'Research information',
                    'Create digital content',
                    'Work collaboratively online',
                ],
                'image_url' => null,
                'photo' => 6,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Technology & Creativity',
                'points' => [
                    'Explore coding concepts',
                    'Design and build projects',
                    'Develop logical thinking',
                    'Solve problems creatively',
                ],
                'image_url' => null,
                'photo' => 6,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Online Safety',
                'points' => [
                    'Protect personal information',
                    'Recognise online risks',
                    'Practise responsible communication',
                    'Build healthy digital habits',
                ],
                'image_url' => null,
                'photo' => 6,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Enterprise & Innovation',
                'points' => [
                    'Explore entrepreneurial ideas',
                    'Understand customer needs',
                    'Plan a simple project',
                    'Present ideas confidently',
                ],
                'image_url' => null,
                'photo' => 6,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
    'specialised-support' => [
        'title' => 'Assessments, Therapy & Specialised Support',
        'description' => 'Access professional assessment and specialist support where additional expertise is needed.',
        'tone' => 'blue',
        'icon' => 'magnifying-glass',
        'photo' => 7,
        'image_url' => null,
        'tagline' => 'Track Progress. Every step of the way.',
        'age_range' => 'For ages 5–25 (Primary to Young Adulthood)',
        'highlights' => [
            'Understand Needs',
            'Expert Guidance',
            'Personalised Support',
            'Track Progress',
        ],
        'benefits' => [
            'A clearer understanding of support needs',
            'Access to qualified professionals',
            'A coordinated approach to support',
            'Clear goals and regular progress reviews',
        ],
        'support_intro' => 'Explore tailored support for your child’s needs, interests and stage of development.',
        'cta_label' => 'Get Connected',
        'cta_route' => 'contact',
        'is_published' => true,
        'areas' => [
            [
                'title' => 'Understand Your Needs',
                'points' => [
                    'Discuss current concerns',
                    'Review strengths and challenges',
                    'Identify suitable assessments',
                    'Plan appropriate next steps',
                ],
                'image_url' => null,
                'photo' => 7,
                'tone' => 'pink',
                'icon' => 'brain',
            ],
            [
                'title' => 'Professional Assessment',
                'points' => [
                    'Connect with qualified specialists',
                    'Understand assessment options',
                    'Receive clear explanations',
                    'Discuss recommendations',
                ],
                'image_url' => null,
                'photo' => 7,
                'tone' => 'blue',
                'icon' => 'bullseye',
            ],
            [
                'title' => 'Individualised Support',
                'points' => [
                    'Explore therapy options',
                    'Agree meaningful goals',
                    'Coordinate with family and school',
                    'Build practical strategies',
                ],
                'image_url' => null,
                'photo' => 7,
                'tone' => 'green',
                'icon' => 'mountain',
            ],
            [
                'title' => 'Review & Progress',
                'points' => [
                    'Track agreed outcomes',
                    'Review support plans',
                    'Share progress with your team',
                    'Adapt support as needs change',
                ],
                'image_url' => null,
                'photo' => 7,
                'tone' => 'purple',
                'icon' => 'people-group',
            ],
        ],
    ],
];
