@extends('development.layout')
@section('title','Provider Matches — Sample')
@section('content')<section class="dark-hero"><p class="eyebrow">RIGHT SUPPORT. BRIGHTER FUTURES.</p><h1>Provider <em>Matches</em></h1><p>Example providers matched to a sample child’s needs.</p></section><div class="tabs" data-provider-categories><button class="active" data-category="all">All Matches (5)</button><button data-category="academic">Academic Support</button><button data-category="emotional">Emotional Wellbeing</button><button data-category="life">Life Skills</button><button data-category="creativity">Creativity</button><button data-category="physical">Physical & Wellness</button></div><div class="grid filter-layout"><aside class="card"><h2>Refine Search</h2><label>Provider name<input id="preview-provider-search" placeholder="Search examples"></label><label>Sort by<select id="preview-provider-sort"><option value="match">Best Match</option><option value="name">Name A–Z</option></select></label><p class="muted">Match percentages are illustrative, as shown in the reference.</p><a class="button secondary wide" href="{{ route('development.providers') }}">View Actual Providers →</a></aside><div id="preview-providers">@foreach([
 ['Peak Performance International','Mindset. Performance. Life Skills.','Nairobi','life academic',96,'Performance Accelerator · Genius Activator · PEAK Club'],
 ['Bright Minds Learning Centre','Personalised learning. Brighter futures.','Westlands','academic',88,'Academic Support · Study Skills · Holiday Revision'],
 ['ThriveWell Counselling & Wellness','Stronger minds. Happier lives.','Lavington','emotional',84,'Emotional Wellbeing · Confidence Coaching'],
 ['Creative Sparks','Discover. Create. Grow.','Karen','creativity',78,'Arts & Creativity · Drama & Public Speaking'],
 ['ActiveKids Kenya','Active bodies. Confident minds.','Runda','physical',72,'Sports Development · Fitness & Wellness']
] as [$name,$description,$location,$category,$score,$programmes])<article class="card provider-row" data-provider data-category="{{ $category }}" data-name="{{ $name }}" data-score="{{ $score }}"><span class="provider-logo">{{ $loop->first?'☆ PEAK':mb_substr($name,0,2) }}</span><div><h3>{{ $name }}</h3><p>{{ $description }}</p><small>⌖ {{ $location }}, Nairobi · Physical & Online</small><p class="pill">{{ $programmes }}</p></div><div class="ring small" style="--score:{{ $score }}"><strong>{{ $score }}%<small>Sample match</small></strong></div><div>@if($loop->first)<a class="button" href="{{ route('development.preview','provider') }}">View Profile →</a>@else<button class="button secondary" data-dialog="Sample provider|This provider is an illustrative reference. Browse actual providers to request a connection.">View Example</button>@endif</div></article>@endforeach<p class="card" id="no-provider-results" hidden>No sample providers match your search.</p></div></div>@endsection
